name: Triplet R&D Demo
on: [push]
jobs:
  build-and-test:
    # to run on our own machines, use runs-on: self-hosted
    runs-on: ubuntu-latest

    # matrix.python-version allows us to test 3.6 and 3.10
    strategy:
      matrix:
        python-version: ['3.6', '3.x']

    # services allows us to have postgres up and running first before executing tests
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    # Actions
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}} 
        architecture: 'x64'
    #   already installed with postgres
    # - name: "Install libpq-dev package"
    #   run: sudo apt-get install libpq-dev

    - name: "Upgrade pip, install venv and activate"
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: "install dependencies from requirements.txt"
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: "run my test script"
      run: |
        source venv/bin/activate
        python ./test_quote_gen.py

    - name: "test postgres instance"
      run: |
        source venv/bin/activate
        python ./db/connect.py