name: Triplet R&D Demo
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: "Install libpq-dev package"
      run: sudo apt-get install libpq-dev

    - name: "Upgrade pip, install venv and activate"
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: "install dependencies from requirements.txt"
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: "run test script"
      run: |
        which python
        which pip
        source venv/bin/activate
        ls -a
        which python
        which pip
        python ./my_script.py